# PostgreSQL

spring.datasource.url=jdbc:postgresql://dpg-d8l3im6gvqtc73ah6m2g-a.oregon-postgres.render.com:5432/incentivos_t91h
spring.datasource.username=incentivos_user
spring.datasource.password=pJIUc5Fq4taXyvFp31YINakdfyYUUkjK

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# Actuator Configuration
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# DevTools Configuration
spring.devtools.restart.enabled=true

# Server Configuration for Dockerfile
server.port=${PORT:8080}
